// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";
import HelloController from "./hello_controller";
import ConfettiController from "./confetti_controller";
import QuickRatingController from "./quick_rating_controller";
import MovieCardController from "./movie_card_controller";
import FlashController from "./flash_controller";

application.register("hello", HelloController);
application.register("confetti", ConfettiController);
application.register("quick-rating", QuickRatingController);
application.register("movie-card", MovieCardController);
application.register("flash", FlashController);
